name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci

      - run: npm run dist

      - uses: ./
        env:
          ACTIONS_STEP_DEBUG: 'true'

      - run: npx prettier --list-different src/**/**.ts

      - run: npx eslint src/**/**.ts __tests__/**/**.ts

      - run: npm test

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Test mypy
        run: |
          pip install mypy
          mypy --show-error-codes __tests__/assets/guinea_pig.py

      - name: Test flake8
        run: |
          pip install flake8
          flake8 __tests__/assets/guinea_pig.py

      - name: Test bandit
        run: |
          pip install bandit
          bandit --format=csv __tests__/assets/guinea_pig.py

      - uses: harveyr/gh-action-publish@releases/v0
        with:
          dirs: dist
        if: contains(github.ref, 'refs/heads/versions/' )
